intents:
  - id: order_status
    description: Retrieve shipping/delivery info for a given order.
    required_params: [order_id]
    tool: check_order_status
    param_mapping:
      # Use double-escaped backslashes with double quotes to avoid YAML escape issues
      order_id: "(?i)\\bO-\\d+\\b"
    constraints:
      channels: [chat]
      rollout: 100
    redaction:
      params: [order_id]
